### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by TheBalkanDev** [GroupeMINASTE/SwiftMC#26]
1. Please put evry single Block into an separate File. It would be more clear.
For example (Grass.swift), NetheriteBlock.swift)

2. Add Items.

3. Add Entitys and AI.

**Comment by TheBalkanDev** [comment]
And yeah before I forgot, why it the ID Limit 256?

**Comment by NathanFallet** [comment]
For entities, see #13 
For blocks, I started (but not ended yet because of time limits) to implement a Spigot-like `Material` class, but for some blocks yeah I will need some extra classes for metadatas (but not necessary for blocks like grass, only for things like chests with real metadatas)
